package bootstrappolicy

const (
	DefaultOpenShiftSharedResourcesNamespace	= "openshift"
	DefaultOpenShiftInfraNamespace			= "openshift-infra"
	DefaultOpenShiftNodeNamespace			= "openshift-node"
)
const (
	DefaultServiceAccountName		= "default"
	BuilderServiceAccountName		= "builder"
	DeployerServiceAccountName		= "deployer"
	MasterUnqualifiedUsername		= "openshift-master"
	AggregatorUnqualifiedUsername		= "openshift-aggregator"
	MasterUsername				= "system:" + MasterUnqualifiedUsername
	AggregatorUsername			= "system:" + AggregatorUnqualifiedUsername
	SystemAdminUsername			= "system:admin"
	MasterProxyUnqualifiedUsername		= "master-proxy"
	MasterProxyUsername			= "system:" + MasterProxyUnqualifiedUsername
	LegacyMasterKubeletAdminClientUsername	= "system:master"
	MasterKubeletAdminClientUsername	= "system:openshift-node-admin"
)
const (
	AuthenticatedGroup	= "system:authenticated"
	AuthenticatedOAuthGroup	= "system:authenticated:oauth"
	UnauthenticatedGroup	= "system:unauthenticated"
	ClusterAdminGroup	= "system:cluster-admins"
	ClusterReaderGroup	= "system:cluster-readers"
	MastersGroup		= "system:masters"
	NodesGroup		= "system:nodes"
	NodeAdminsGroup		= "system:node-admins"
)
const (
	InfraNodeBootstrapServiceAccountName = "node-bootstrapper"
)
const (
	ClusterAdminRoleName			= "cluster-admin"
	SudoerRoleName				= "sudoer"
	ScopeImpersonationRoleName		= "system:scope-impersonation"
	ClusterReaderRoleName			= "cluster-reader"
	StorageAdminRoleName			= "storage-admin"
	ClusterDebuggerRoleName			= "cluster-debugger"
	AdminRoleName				= "admin"
	EditRoleName				= "edit"
	ViewRoleName				= "view"
	AggregatedAdminRoleName			= "system:openshift:aggregate-to-admin"
	AggregatedEditRoleName			= "system:openshift:aggregate-to-edit"
	AggregatedViewRoleName			= "system:openshift:aggregate-to-view"
	AggregatedClusterReaderRoleName		= "system:openshift:aggregate-to-cluster-reader"
	SelfProvisionerRoleName			= "self-provisioner"
	BasicUserRoleName			= "basic-user"
	StatusCheckerRoleName			= "cluster-status"
	SelfAccessReviewerRoleName		= "self-access-reviewer"
	RegistryAdminRoleName			= "registry-admin"
	RegistryViewerRoleName			= "registry-viewer"
	RegistryEditorRoleName			= "registry-editor"
	TemplateServiceBrokerClientRoleName	= "system:openshift:templateservicebroker-client"
	BuildStrategyDockerRoleName		= "system:build-strategy-docker"
	BuildStrategyCustomRoleName		= "system:build-strategy-custom"
	BuildStrategySourceRoleName		= "system:build-strategy-source"
	BuildStrategyJenkinsPipelineRoleName	= "system:build-strategy-jenkinspipeline"
	ImageAuditorRoleName			= "system:image-auditor"
	ImagePullerRoleName			= "system:image-puller"
	ImagePusherRoleName			= "system:image-pusher"
	ImageBuilderRoleName			= "system:image-builder"
	ImagePrunerRoleName			= "system:image-pruner"
	ImageSignerRoleName			= "system:image-signer"
	DeployerRoleName			= "system:deployer"
	RouterRoleName				= "system:router"
	RegistryRoleName			= "system:registry"
	MasterRoleName				= "system:master"
	SDNReaderRoleName			= "system:sdn-reader"
	SDNManagerRoleName			= "system:sdn-manager"
	OAuthTokenDeleterRoleName		= "system:oauth-token-deleter"
	WebHooksRoleName			= "system:webhook"
	DiscoveryRoleName			= "system:openshift:discovery"
	NodeAdminRoleName			= "system:node-admin"
	NodeReaderRoleName			= "system:node-reader"
	OpenshiftSharedResourceViewRoleName	= "shared-resource-viewer"
	NodeBootstrapRoleName			= "system:node-bootstrapper"
	NodeConfigReaderRoleName		= "system:node-config-reader"
)
const (
	SelfAccessReviewerRoleBindingName		= SelfAccessReviewerRoleName + "s"
	SelfProvisionerRoleBindingName			= SelfProvisionerRoleName + "s"
	DeployerRoleBindingName				= DeployerRoleName + "s"
	ClusterAdminRoleBindingName			= ClusterAdminRoleName + "s"
	ClusterReaderRoleBindingName			= ClusterReaderRoleName + "s"
	BasicUserRoleBindingName			= BasicUserRoleName + "s"
	OAuthTokenDeleterRoleBindingName		= OAuthTokenDeleterRoleName + "s"
	StatusCheckerRoleBindingName			= StatusCheckerRoleName + "-binding"
	ImagePullerRoleBindingName			= ImagePullerRoleName + "s"
	ImageBuilderRoleBindingName			= ImageBuilderRoleName + "s"
	MasterRoleBindingName				= MasterRoleName + "s"
	NodeProxierRoleBindingName			= "system:node-proxier" + "s"
	NodeAdminRoleBindingName			= NodeAdminRoleName + "s"
	SDNReaderRoleBindingName			= SDNReaderRoleName + "s"
	WebHooksRoleBindingName				= WebHooksRoleName + "s"
	OpenshiftSharedResourceViewRoleBindingName	= OpenshiftSharedResourceViewRoleName + "s"
	BuildStrategyDockerRoleBindingName		= BuildStrategyDockerRoleName + "-binding"
	BuildStrategySourceRoleBindingName		= BuildStrategySourceRoleName + "-binding"
	BuildStrategyJenkinsPipelineRoleBindingName	= BuildStrategyJenkinsPipelineRoleName + "-binding"
)
const (
	DockerBuildResource		= "builds/docker"
	OptimizedDockerBuildResource	= "builds/optimizeddocker"
	SourceBuildResource		= "builds/source"
	CustomBuildResource		= "builds/custom"
	JenkinsPipelineBuildResource	= "builds/jenkinspipeline"
	NodeMetricsSubresource		= "metrics"
	NodeStatsSubresource		= "stats"
	NodeSpecSubresource		= "spec"
	NodeLogSubresource		= "log"
)
